apiVersion: v1
kind: Secret
metadata:
  name: mysql-config
  namespace: yonecloud
data:
  DATABASE: ${MYSQL_DATABASE_SECRET}
  PASSWORD: ${MYSQL_PASSWORD_SECRET}
---
apiVersion: v1
kind: Service
metadata:
  name: yone-mysql-svc
  namespace: yonecloud
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yone-mysql
  namespace: yonecloud
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:${MYSQL_VERSION}
          name: mysql
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          ports:
            - containerPort: 3306
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 3306
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-config
                  key: DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-config
                  key: PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: mysql-k8s-volume
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 30Gi
                volumeMode: Filesystem