apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-reloader-sa
  namespace: yonecloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-reloader-role
  namespace: yonecloud
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-reloader-rb
  namespace: yonecloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-reloader-role
subjects:
  - kind: ServiceAccount
    name: config-reloader-sa
    namespace: yonecloud