{
 "title": "首页",
 "tags": [ "home" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "功能展示", "type": "dashlist", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 } },
  { "title": "数据源展示", "type": "dashlist", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 } },
  {
   "title": "业务展示",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_build_info) by (business)"
    }
   ]
  },
  {
   "title": "总主机数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_build_info)" }
   ]
  },
  {
   "title": "异常主机数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(up == 0)" }
   ]
  },
  {
   "title": "服务器每秒接收的请求",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_count",
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "进程占用内存 / CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes",
     "legendFormat": "memory",
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "启动goroutine数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines",
     "legendFormat": "goroutines",
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    }
   ]
  },
  {
   "title": "各个模块连接数/5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_established_total[5m])",
     "legendFormat": "{{dialer_name}}",
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    }
   ]
  },
  {
   "title": "请求状态",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total[5m])",
     "legendFormat": "{{code}}",
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    }
   ]
  }
 ]
}