{
 "title": "主机资源监控",
 "tags": [ "node" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP地址",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "基本信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "启动时间",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "总内存",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU核数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
      }
     ]
    },
    {
     "title": "CPU iowait",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "总文件描述符",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "可用的inode",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(node_filesystem_files_free{instance=~\"$node\", fstype=~\"ext.?|xfs\"})"
      }
     ]
    }
   ]
  },
  { "title": "监控信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU占用(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "已用磁盘空间",
   "type": "table",
   "description": "在这个看板中：总磁盘、使用率、可用率和使用率与df命令的Size、Used、Avail和Use%列的值一致，Use%的值将四舍五入到小数点后一位，这样会更准确。\n注：df中Use%算法为：（(size-free) * 100 / (avail + (size-free))，结果可被此值整除，不可被此值整除为+1，结果单位为%。",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU核数"
    }
   ]
  },
  {
   "title": "磁盘读/写(每秒)字节数",
   "type": "graph",
   "description": "每秒读/写字节数",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读 bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写 bytes"
    }
   ]
  },
  {
   "title": "磁盘IOPS(已完成)",
   "type": "graph",
   "description": "每秒读/写完成次数",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bps", "label": "下载（-）/上传（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_上传"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_下载"
    }
   ]
  },
  {
   "title": "打开文件描述符（左）/上下文切换次数（右）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "TCP连接",
   "type": "graph",
   "description": "当前正在使用的套接字",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "每小时网络流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "花费时间I/Os",
   "type": "graph",
   "description": "每秒 I/O 消费的时间",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "磁盘读/写花费的时间",
   "type": "graph",
   "description": "每秒读/写操作所花费的时间",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "s", "label": "Time read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读 time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写 time"
    }
   ]
  }
 ]
}