{
 "title": "网络设备监控",
 "description": "网络设备监控，如交换机、路由器等",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "Interface",
    "label": "接口",
    "query": {
     "query": "query_result(ifHCInOctets{instance=\"$instance\",ifIndex !~ \"1|2|3\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "启动时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\",job=\"$Job\"}",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "最大出流量(当前)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$instance\",job=\"$Job\"}[5m]))"
    }
   ]
  },
  {
   "title": "最大入流量 (当前)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$instance\",job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "总出流量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$instance\",job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "总入流量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$instance\",job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "$Interface In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-irate(ifHCInOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[5m])",
     "legendFormat": "{{ifName}} In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[5m])",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "$instance Total In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(job,instance)(irate(ifHCOutOctets{job='snmp',instance='$instance'}[5m]))",
     "legendFormat": "$instance Total Out"
    },
    {
     "expr": "sum by(job,instance)(irate(ifHCInOctets{job='snmp',instance='$instance'}[5m]))",
     "legendFormat": "$instance Total In"
    }
   ]
  },
  { "title": "接口状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "接口状态",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\",job=\"$Job\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$instance\",job=\"$Job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{instance=\"$instance\",job=\"$Job\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{instance=\"$instance\",job=\"$Job\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{instance=\"$instance\",job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  { "title": "接口利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$Interface",
   "type": "graph",
   "description": "接口利用率",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(ifHCInOctets{job=\"snmp\",ifName=\"$Interface\",instance=\"$instance\"}[2m])) * 8 / ((ifHighSpeed{job=\"snmp\",ifName=\"$Interface\",instance=\"$instance\"})*1000000)*100",
     "legendFormat": "$Interface In"
    },
    {
     "expr": "(rate(ifHCOutOctets{job=\"snmp\",ifName=\"$Interface\",instance=\"$instance\"}[2m])) * 8 / ((ifHighSpeed{job=\"snmp\",ifName=\"$Interface\",instance=\"$instance\"})*1000000)*100",
     "legendFormat": "$Interface Out"
    }
   ]
  },
  {
   "title": "$Interface",
   "type": "graph",
   "description": "接口阻塞大小",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "repeat": "Interface",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job='snmp',ifName=~'$Interface',instance=\"$instance\"}[5m])",
     "legendFormat": "Out"
    },
    {
     "expr": "irate(ifHCInOctets{job='snmp',ifName=~'$Interface',instance=\"$instance\"}[5m])",
     "legendFormat": "In"
    }
   ]
  }
 ]
}